WIP: remove Env data-type
PoignardAzur/masonry-rs pull request #53
Opened 2024-03-07 09:17 UTC by herkhinah

I've refactored out the Env data type, the examples still seem to run.

2024-03-15 14:49 UTC, PoignardAzur commented
Sorry for the late reply, I've been on vacation. I've only had time to skim this, but it looks like a clean refactor. Pretty high-quality contribution!

I've noticed a `// TODO remove env` in `widget/flex.rs` that you probably didn't mean to leave.

I'll take another look at this soon, and after that, we'll try to get this PR merged ASAP.

2024-03-16 12:58 UTC, PoignardAzur requested changes
Overall this seems like a clean set of changes. Once the items I mentioned are addressed, and the rustfmt and clippy errors are fixed, we can merge this ASAP.

By the way, please make sure to do any followup fixes in a separate commit (eg don't use rebase or `git commit --amend`) so the fixes don't get lost in this PR's huge changeset.

2024-03-16 12:58 UTC, PoignardAzur commented on src/widget/flex.rs
>          if env.get(Env::DEBUG_PAINT) && ctx.widget_state.baseline_offset != 0.0 {
The refactor needs to address these kinds of cases. I'd suggest adding `debug_paint` and `debug_widget_id` bool attributes to GlobalPassCtx and going from there.

2024-03-16 12:58 UTC, PoignardAzur commented on src/widget/widget_pod.rs
> +            /*
See above.

2024-03-16 12:58 UTC, PoignardAzur commented on src/widget/widget_pod.rs
> +        /*
See above.

2024-03-16 12:58 UTC, PoignardAzur commented on src/widget/widget_pod.rs
> +            /*
See above.

2024-03-16 12:58 UTC, PoignardAzur commented on src/text/rich_text.rs
> +impl Eq for RichText {}
This is an invalid implementation of `Eq` and a dubious implementation of `PartialEq`. Two buffers with different pointer values but identical content shouldn't return false in PartialEq.

As a placeholder solution, I'd suggest adding a function called eg `maybe_eq` to the TextStorage trait with the same semantic as the now-removed `Data::same()`. We can think of a better design once this is merged.

2024-03-24 12:11 UTC, PoignardAzur commented
FYI, I might rebase this PR on my side (or straight-up redo it from scratch) next week, since I'm actively working on Masonry now.

2024-03-26 11:39 UTC, closed without merging

2024-03-26 14:25 UTC, PoignardAzur commented
I've done a bunch of changes on top of this PR and merged them. Thanks for the contribution!

2024-03-28 09:56 UTC, herkhinah commented
Sry for not responding. I’m currently homeless for an unknown amount of time.Sent from my iPhoneOn 26. Mar 2024, at 15:25, Olivier FAURE ***@***.***> wrote:﻿
I've done a bunch of changes on top of this PR and merged them. Thanks for the contribution!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-28 11:16 UTC, PoignardAzur commented
Shit. Good luck then.